version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
