import FormView, { FormFieldValuesType, FormValueType } from '@/components/builder/components/FormView';
import Brand from '@/components/common/Brand';
import { useGetFormQuery, useSubmitFormMutation } from '@/state/apiSlices/formsApi';
import { useEffect } from 'react';
import { useParams } from 'react-router-dom'

const PageForm = () => {

  const { formId } = useParams<{ formId: string }>()

  // RTK Query hook to get the form settings
  const { data: form, isLoading: isDataLoading, isSuccess } = useGetFormQuery({
    formId: formId ?? '',
    schema: true
  }, {
    skip: !formId
  });

  // submit form mutation
  const [submitForm, { isLoading, isSuccess: isSubmissionSuccess }] = useSubmitFormMutation()

  useEffect(() => {
    if (isSubmissionSuccess) {
      //TODO: Redirect to success page
      alert('Form submitted successfully')
    }
  }, [isSubmissionSuccess])

  const sendFormData = (formId: string, values: FormFieldValuesType): void => {
    
    // prepare form data
    let formData = new FormData();
    Object.keys(values).forEach(key => {
      const value = values[key] as string | Blob;
      if (value) {
        formData.append(key, value);
      } else {
        console.error(`Value for ${key} is undefined or null.`);
      }
    });

    submitForm({ formId: formId, formData: formData });
  };

  return (
    <div className='overflow-y-hidden min-h-screen flex flex-col justify-between gap-2'>
      {
        isDataLoading && <div>Loading...</div>
      }
      {
        !isSuccess && <div>Something went wrong</div>
      }
      {
        !form && <div>Form not found</div>
      }
      {
        form && <FormView form={form!} submitFormHandler={sendFormData} />
      }
      <div className="mt-12">
        <Footer />
      </div>
    </div>
  )
}

// Never submit passwords through Forms generated by Research Data Collector Platform.
// This content is neither created nor endorsed by Research Data Collector Platform.
const Footer = () => {
  return (
    <div className='w-full border-t border-gray-300'>
      <div className='container mx-auto py-4'>
        <div className="transform scale-50">
          <Brand />
        </div>
      </div>
    </div>
  )
}

export default PageForm


